// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    toObjectAtDepth: function(depth) {
      if (depth === 0) {
        return this.toObject();
      } else {
        return {
          description: this.description,
          sshUrl: this.sshUrl,
          webUrl: this.webUrl,
          mergeRequestsEnabled: this.mergeRequestsEnabled,
          wikiEnabled: this.wikiEnabled,
          createdDate: this.createdDate,
          lastActivityDate: this.lastActivityDate,
          namespace: this.namespace.name
        };
      }
    },
    getName: function(forceNoun) {
      var name;
      if (forceNoun == null) {
        forceNoun = false;
      }
      name = this.host || '';
      if (forceNoun) {
        name += ' repo';
      }
      return name;
    },
    getNameRegexString: function() {
      return this.host + "(?: repo(sitory)?)?";
    }
  };

}).call(this);
