// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    getName: function(forceNoun) {
      var m;
      if (forceNoun == null) {
        forceNoun = false;
      }
      if (forceNoun) {
        if (!this.role) {
          return 'some kind of server';
        } else if (m = this.role.match(/^([a-z\-]+)(\d+)$/i)) {
          return m[1] + " server " + m[2];
        } else {
          return this.role + " server";
        }
      } else {
        return this.role;
      }
    },
    getNameRegexString: function() {
      return this.role + "(?: server)?";
    }
  };

}).call(this);
