// Generated by CoffeeScript 1.10.0
(function() {
  var carSchema, extend, mongoose;

  mongoose = require('mongoose');

  extend = require('lodash.assignin');

  carSchema = mongoose.Schema({
    reg: String,
    colour: {
      type: String,
      crater: {
        suggestions: true
      }
    },
    make: {
      type: String,
      crater: {
        suggestions: true
      }
    },
    model: {
      type: String,
      crater: {
        suggestions: true
      }
    }
  }, {
    crater: {
      name: 'Car'
    }
  });

  extend(carSchema.statics, require('./methods/static/Base'));

  extend(carSchema.methods, require('./methods/instance/Base'));

  module.exports = carSchema;

}).call(this);
