// Generated by CoffeeScript 1.10.0
(function() {
  var customerSchema, extend, mongoose, projectSchema, slug;

  mongoose = require('mongoose');

  projectSchema = require('./Project');

  extend = require('lodash.assignin');

  slug = require('slug');

  customerSchema = mongoose.Schema({
    name: String,
    _codename: {
      type: String,
      crater: {
        virtual: 'codename'
      }
    },
    aliases: [String],
    projects: [projectSchema],
    slackChannel: String
  }, {
    crater: {
      name: 'Customer'
    }
  });

  customerSchema.virtual('codename').get(function() {
    return this._codename || slug(customerSchema.statics.simplifyName(this.name).toLowerCase());
  }).set(function(value) {
    return this._codename = value;
  });

  customerSchema.virtual('project', {
    _jiri_aliasTarget: 'projects'
  }).get(function() {
    return this.getProject();
  });

  customerSchema.virtual('alias', {
    _jiri_aliasTarget: 'aliases'
  }).get(function() {
    return this.aliases;
  });

  extend(customerSchema.statics, require('./methods/static/Base'), require('./methods/static/Entity'), require('./methods/static/Customer'));

  extend(customerSchema.methods, require('./methods/instance/Base'), require('./methods/instance/Customer'));

  customerSchema.post('save', (function(_this) {
    return function(doc) {
      return customerSchema.statics.getAllNameRegexString(true);
    };
  })(this));

  module.exports = customerSchema;

}).call(this);
