// Generated by CoffeeScript 1.10.0
(function() {
  var carSchema, extend, mongoose, personSchema;

  mongoose = require('mongoose');

  extend = require('lodash.assignin');

  carSchema = require('./Car');

  personSchema = mongoose.Schema({
    name: String,
    email: String,
    cars: [carSchema],
    team: {
      type: String,
      crater: {
        suggestions: true
      }
    }
  }, {
    crater: {
      name: 'Person'
    }
  });

  personSchema.virtual('car', {
    _jiri_aliasTarget: 'cars'
  }).get(function() {
    return this.getDefault('cars');
  });

  extend(personSchema.statics, require('./methods/static/Base'), require('./methods/static/Entity'));

  extend(personSchema.methods, require('./methods/instance/Base'));

  module.exports = personSchema;

}).call(this);
