// Generated by CoffeeScript 1.10.0
(function() {
  var extend, mongoose, serverSchema;

  mongoose = require('mongoose');

  extend = require('lodash.assignin');

  serverSchema = mongoose.Schema({
    role: {
      type: String,
      crater: {
        suggestions: true
      }
    },
    host: String
  }, {
    crater: {
      name: 'Server'
    }
  });

  extend(serverSchema.statics, require('./methods/static/Base'), require('./methods/static/Server'));

  extend(serverSchema.methods, require('./methods/instance/Base'), require('./methods/instance/Server'));

  module.exports = serverSchema;

}).call(this);
