// Generated by CoffeeScript 1.11.1
(function() {
  var extend, mongoose, softwareSchema;

  mongoose = require('mongoose');

  extend = require('lodash.assignin');

  softwareSchema = mongoose.Schema({
    name: {
      type: String,
      crater: {
        suggestions: true
      }
    },
    version: String
  }, {
    crater: {
      name: 'Software'
    }
  });

  extend(softwareSchema.statics, require('./methods/static/Base'));

  extend(softwareSchema.methods, require('./methods/instance/Base'));

  module.exports = softwareSchema;

}).call(this);
