// Generated by CoffeeScript 1.10.0
(function() {
  var mongoose;

  mongoose = require('mongoose');

  module.exports = {
    getSchemas: function() {
      if (!this.schemas) {
        this.schemas = {
          Customer: require('./schema/Customer'),
          Project: require('./schema/Project'),
          Stage: require('./schema/Stage'),
          Server: require('./schema/Server'),
          Software: require('./schema/Software'),
          Repository: require('./schema/Repository'),
          Car: require('./schema/Car'),
          Person: require('./schema/Person')
        };
      }
      return this.schemas;
    },
    getSchema: function(name) {
      var schemas;
      schemas = this.getSchemas();
      return schemas[name];
    },
    getModels: function() {
      var name, ref, schema;
      if (!this.models) {
        this.models = {};
        ref = this.getSchemas();
        for (name in ref) {
          schema = ref[name];
          this.models[name] = mongoose.model(name, schema);
        }
      }
      return this.models;
    },
    getModel: function(name) {
      var models;
      models = this.getModels();
      return models[name];
    }
  };

}).call(this);
