// Generated by CoffeeScript 1.11.1
(function() {
  var SubTargetMatch;

  SubTargetMatch = (function() {
    function SubTargetMatch(options) {
      var i, len, p, ref;
      this.target = options.target, this.keyword = options.keyword, this.query = options.query, this.property = options.property, this.label = options.label;
      ref = ['target', 'keyword', 'query', 'property'];
      for (i = 0, len = ref.length; i < len; i++) {
        p = ref[i];
        if (p == null) {
          throw "SubTargetMatch." + p + " is required";
        }
      }
    }

    return SubTargetMatch;

  })();

  module.exports = SubTargetMatch;

}).call(this);
